run restore (fix CI/CD error)
the error seems to happen only on the CI/CD
2020-08-19T09:16:58.9125156Z 09:16:58.836 INFO  "D:\a\1\s\junit699738301414415543\MultipleProjects\MultipleProjects.sln" (Rebuild target) (1) ->
2020-08-19T09:16:58.9126794Z 09:16:58.836 INFO  "D:\a\1\s\junit699738301414415543\MultipleProjects\SecondProjectTests\SecondProjectTests.csproj" (Rebuild target) (5) ->
2020-08-19T09:16:58.9141998Z 09:16:58.836 INFO    C:\Program Files\dotnet\sdk\3.1.302\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(234,5): error NETSDK1004: Assets file 'D:\a\1\s\junit699738301414415543\MultipleProjects\SecondProjectTests\obj\project.assets.json' not found. Run a NuGet package restore to generate this file. [D:\a\1\s\junit699738301414415543\MultipleProjects\SecondProjectTests\SecondProjectTests.csproj]

And
2020-08-19T09:16:58.8593809Z 09:16:58.835 INFO    obj\Debug\netstandard2.0\.NETStandard,Version=v2.0.AssemblyAttributes.cs(4,20): error CS0400: The type or namespace name 'System' could not be found in the global namespace (are you missing an assembly reference?) [D:\a\1\s\junit699738301414415543\MultipleProjects\SecondProject\SecondProject.csproj]